'use strict';function w(e,a,b,d,g){e.u.qc(e.cb,a,b,d,g)}function H(e,a,b,d){e.u.$?w(e,a,b,d):e.u.sf()._OnMessageFromDOM({type:"event",component:e.cb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function I(e,a,b){e.u.C(e.cb,a,b)}function J(e,a){for(const [b,d]of a)I(e,b,d)}function L(e){e.Tb||(e.u.bf(e.le),e.Tb=!0)}window.Ea=class{constructor(e,a){this.u=e;this.cb=a;this.Tb=!1;this.le=()=>this.ua()}kd(){}ua(){}};function M(e){-1!==e.Sa&&(self.clearTimeout(e.Sa),e.Sa=-1)}
window.Se=class{constructor(e,a){this.Qc=e;this.Fg=a;this.Sa=-1;this.Ub=-Infinity;this.me=()=>{this.Sa=-1;this.Ub=Date.now();this.ib=!0;this.Qc();this.ib=!1};this.Ud=this.ib=!1}c(){M(this);this.me=this.Qc=null}};"use strict";function O(e,a){const b=a.elementId,d=e.od(b);e.V.set(b,d);a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{P(e,"elem-focused",b)});d.addEventListener("blur",()=>{P(e,"elem-blurred",b)});e.bb&&document.body.appendChild(d)}
function Q(e,a,b){I(e,a,d=>{const g=e.V.get(d.elementId);return b(g,d)})}function P(e,a,b,d){d||(d={});d.elementId=b;w(e,a,d)}
window.Fe=class extends self.Ea{constructor(e,a){super(e,a);this.V=new Map;this.bb=!0;J(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.V.get(b);this.qd(d);this.bb&&d.parentElement.removeChild(d);this.V.delete(b)}}],["set-visible",b=>{this.bb&&(this.V.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.bb){var d=this.V.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";
b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.V.get(b.elementId);this.Ad()}],["focus",b=>this.Jc(b)],["set-css-style",b=>{this.V.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.V.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.V.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}od(){throw Error("required override");}qd(){}Ad(){throw Error("required override");}Jc(e){var a=this.V.get(e.elementId);e.focus?
a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Rg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Vg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,g=!1;function n(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(m){}d=!0}return g}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=
await x(m);return(new TextDecoder("utf-8")).decode(m)}function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let K=0;const N=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");N.push(m)};const f=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.fa=class m{constructor(c){this.$=
c.Xg;this.pa=null;this.F="";this.dc=c.Ug;this.xb={};this.La=this.wb=null;this.Rb=[];this.lb=this.K=this.Qa=null;this.Pa=-1;this.Kg=()=>this.Qf();this.Oa=[];this.s=c.ne;this.jb="file"===location.protocol.substr(0,4);!this.$||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.$=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.$=!1;if("cordova"===this.s&&this.$)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.$=!1)}else this.$=!1;this.Wb=this.ia=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.jb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.Af(k));this.C("runtime","create-job-worker",()=>this.Bf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Gd(c)):this.Gd(c)}c(){this.xc();this.pa&&(this.pa=this.pa.onmessage=
null);this.wb&&(this.wb.terminate(),this.wb=null);this.La&&(this.La.c(),this.La=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}ud(){return e&&"cordova"===this.s}pc(){const c=navigator.userAgent;return e&&f.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Gd(c){"macos-wkwebview"===this.s&&this.Nc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Wb={};await this.gf();for(let l=0,p=c.Ta.length;l<p;++l){var k=c.Ta[l].toLowerCase();
this.Wb.hasOwnProperty(k)?c.Ta[l]={Rg:!0,Vg:this.Wb[k]}:this.ia.hasOwnProperty(k)&&(c.Ta[l]=URL.createObjectURL(this.ia[k]))}}c.Mg?this.F=c.Mg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Zg&&(this.xb=c.Zg);k=new MessageChannel;this.pa=k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Mf(l));this.lb=new self.Oe(this);await R(this.lb);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.$?await this.vf(c,k.port2):await this.uf(c,k.port2)}Ac(c){c=this.xb.hasOwnProperty(c)?this.xb[c]:c.endsWith("/workermain.js")&&this.xb.hasOwnProperty("workermain.js")?this.xb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async jc(c,k,
l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.jb)return c=await this.yb(l.Qg?c:this.dc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}Ed(c){var k=
this.lb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Wa(),projectData:c.fh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.dh||"",exportType:c.ne,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.eh,jobScheduler:{inputPort:k.Wc,outputPort:k.cd,maxNumWorkers:k.Hg},supportedAudioFormats:B,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.dc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.dc+"opus.wasm.wasm",isFileProtocol:this.jb,isiOSCordova:this.ud(),isiOSWebView:this.pc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async vf(c,k){var l=this.Ac(c.Yg);this.wb=await this.jc(l,this.F,{type:"module",name:"Runtime",Qg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);
window.c3canvas=this.K;let p=c.jd||[],t=c.Ta;p=await Promise.all(p.map(r=>this.Ha(r)));t=await Promise.all(t.map(r=>this.Ha(r)));if("cordova"===this.s)for(let r=0,u=c.hc.length;r<u;++r){const z=c.hc[r],G=z[0];if(G===c.gd||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))z[1]=await this.Ha(G)}this.wb.postMessage(Object.assign(this.Ed(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:t,projectScripts:c.hc,mainProjectScript:c.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...S(this.lb)]);this.Rb=E.map(r=>new r(this));this.Dd();self.c3_callFunction=(r,u)=>this.Qa.wf(r,u);"preview"===this.s&&(self.goToLastErrorScript=()=>this.qc("runtime","go-to-last-error-script"))}async uf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Rb=E.map(r=>new r(this));this.Dd();var l=c.Ta.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.jd)&&l.unshift(...c.jd);l=await Promise.all(l.map(r=>
this.Ha(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const p=c.gd,t=c.hc;for(let [r,u]of t)if(u||(u=r),r===p)try{u=await this.Ha(u),await b(u),"preview"!==this.s||l[r]||this.Pd(r,"main script did not run to completion")}catch(z){this.Pd(r,z)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))u=await this.Ha(u),await b(u);"preview"===this.s&&"object"!==typeof self.$g.ah?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ed(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:N}),this.Jd(),this.La=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.La,c))}Pd(c,k){this.Kb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Jd(){this.Kb()}Kb(){const c=
window.Ng;c&&(c.parentElement.removeChild(c),window.Ng=null)}async Bf(){const c=await T(this.lb);return{outputPort:c,transferables:[c]}}sf(){if(this.$)throw Error("not available in worker mode");return this.La}qc(c,k,l,p,t){this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},t)}vd(c,k,l,p,t){const r=K++,u=new Promise((z,G)=>{F.set(r,{resolve:z,reject:G})});this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
t);return u}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Gf(c);if("result"===k)this.Tf(c);else if("runtime-ready"===k)this.Uf();else if("alert-error"===k)this.Kb(),alert(c.message);else if("creating-runtime"===k)this.Jd();else throw Error(`unknown message '${k}'`);}Gf(c){const k=c.component,l=c.handler,p=c.data,t=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(u){console.error(`Exception in '${k}' handler '${l}':`,u);null!==t&&this.Jb(t,!1,""+u);return}if(null===
t)return r;r&&r.then?r.then(u=>this.Jb(t,!0,u)).catch(u=>{console.error(`Rejection from '${k}' handler '${l}':`,u);this.Jb(t,!1,""+u)}):this.Jb(t,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Tf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Da(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}Dd(){for(const c of this.Rb)if("runtime"===c.cb){this.Qa=c;return}throw Error("cannot find runtime DOM handler");}Mf(c){this.qc("debugger","message",c)}Uf(){for(const c of this.Rb)c.kd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Lb(c){h=!!c}bf(c){this.Oa.push(c);this.Mc()}fg(c){c=this.Oa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Oa.splice(c,1);this.Oa.length||this.xc()}Mc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Kg))}xc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Qf(){this.Pa=-1;for(const c of this.Oa)c();this.Mc()}va(c){this.Qa.va(c)}Ga(c){this.Qa.Ga(c)}Lc(){this.Qa.Lc()}Eb(c){this.Qa.Eb(c)}Ne(){return!!B["audio/webm; codecs=opus"]}async Dg(c){c=await this.vd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Me(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}td(c){return!this.Me(c)}async Ha(c){return"cordova"===this.s&&(c.startsWith("file:")||this.jb&&this.td(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.yb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Af(c){const k=c.filename;switch(c.as){case "text":return await this.Ee(k);case "buffer":return await this.yb(k);
default:throw Error("unsupported type");}}Fd(){const c=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof c)throw Error("Permission API is not loaded");return c}Id(c,k){c=c[k];if("string"!==typeof c)throw Error("Invalid permission name");return c}tf(c){const k=this.Fd();return new Promise((l,p)=>k.checkPermission(this.Id(k,c),t=>l(!!t.hasPermission),p))}gg(c){const k=this.Fd();return new Promise((l,p)=>k.requestPermission(this.Id(k,c),t=>l(!!t.hasPermission),
p))}async Ve(c){if("cordova"!==this.s||this.ud())return!0;for(const k of c)if(!await this.tf(k)&&!1===await this.gg(k))return!1;return!0}async sc(...c){if(!1===await this.Ve(c))throw Error("Permission not granted");}nd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,p)},p)})}async Ee(c){c=await this.nd(c);return await D(c)}yc(){if(y.length&&!(8<=C)){C++;var c=y.shift();this.hf(c.filename,c.Wg,c.Pg)}}yb(c){return new Promise((k,
l)=>{y.push({filename:c,Wg:p=>{C--;this.yc();k(p)},Pg:p=>{C--;this.yc();l(p)}});this.yc()})}async hf(c,k,l){try{const p=await this.nd(c),t=await x(p);k(t)}catch(p){l(p)}}Nc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async gf(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.ff(k,l));await Promise.all(c)}async ff(c,
k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Wb[c]=k.str;else{let l=await this.qf(k);l||(l=this.kf(k));this.ia[c]=l}}async qf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}kf(c){c=this.$f(c);return this.ef(c.data,c.Sg)}$f(c){var k=c.indexOf(",");
if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Sg:c,data:l}}ef(c,k){var l=c.length;let p=l>>2,t=new Uint8Array(l),r=new Uint32Array(t.buffer,0,p),u,z;for(z=u=0;u<p;++u)r[u]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)t[z]=c.charCodeAt(z),++z;return new Blob([t],{type:k})}}}"use strict";
{const e=self.fa;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(f){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=f;document.head.appendChild(c)})}function v(f){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=f})}async function B(f){f=URL.createObjectURL(f);try{return await v(f)}finally{URL.revokeObjectURL(f)}}function D(f){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(f)})}async function x(f,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(f);var c=await D(f);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(f)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);f=new Blob([c],{type:"image/svg+xml"});return await B(f)}function y(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(f){E.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function F(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await B(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,m,c,k){f=await x(f,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(f,0,0,h,m);return l};let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);function N(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.Da(class extends self.Ea{constructor(f){super(f,"runtime");this.Zd=!0;this.Ra=-1;this.ed="any";this.Qd=this.Rd=!1;this.Zc=
this.tb=this.za=null;f.C("canvas","update-size",c=>this.Xf(c));f.C("runtime","invoke-download",c=>this.Kf(c));f.C("runtime","raster-svg-image",c=>this.Rf(c));f.C("runtime","get-svg-image-size",c=>this.If(c));f.C("runtime","set-target-orientation",c=>this.Vf(c));f.C("runtime","register-sw",()=>this.Sf());f.C("runtime","post-to-debugger",c=>this.Ld(c));f.C("runtime","go-to-script",c=>this.Ld(c));f.C("runtime","before-start-ticking",()=>this.zf());f.C("runtime","debug-highlight",c=>this.Cf(c));f.C("runtime",
"enable-device-orientation",()=>this.df());f.C("runtime","enable-device-motion",()=>this.cf());f.C("runtime","add-stylesheet",c=>this.yf(c));f.C("runtime","alert",c=>this.Ec(c));f.C("runtime","hide-cordova-splash",()=>this.Jf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=f.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.qb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Yf());window.addEventListener("fullscreenchange",
()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",c=>this.Gc(c));window.addEventListener("webkitfullscreenerror",c=>this.Gc(c));window.addEventListener("mozfullscreenerror",c=>this.Gc(c));f.pc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Zf(c);this.Ma=new Set;this.Xb=new WeakSet;this.oa=!1}zf(){"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Kc(!0)),document.addEventListener("resume",()=>this.Kc(!1))):document.addEventListener("visibilitychange",()=>this.Kc(document.hidden));return{isSuspended:!(!document.hidden&&!K)}}kd(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:N()});this.qb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Kd("keydown",h));window.addEventListener("keyup",h=>this.Kd("keyup",h));window.addEventListener("dblclick",h=>this.Hc("dblclick",h,d));window.addEventListener("wheel",h=>this.Of(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Bc(h);this.Za("pointerdown",h)}),this.u.$&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.tb=new self.Se(()=>this.nf(),5),this.tb.Ud=!0,window.addEventListener("pointerrawupdate",h=>this.Pf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Bc(h);this.Ic("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Ic("pointermove",h)),window.addEventListener("mouseup",h=>this.Ic("pointerup",h)),window.addEventListener("touchstart",h=>{this.Bc(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const f=()=>this.Lc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}$a(f,h){w(this,f,h||null,n)}xa(){return this.u.xa()}wa(){return this.u.wa()}Yf(){const f=this.xa(),h=this.wa();this.$a("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()});this.u.pc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Md(f,h,0))}hg(f,h,m){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Md(f,
h,m),48)}Md(f,h,m){const c=this.xa(),k=this.wa();this.Ra=-1;c!=f||k!=h?this.$a("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()}):10>m&&this.hg(c,k,m+1)}Vf(f){this.ed=f.targetOrientation}zg(){const f=this.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const f=e.Wa();f&&"any"!==this.ed&&this.zg();w(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.xa(),innerHeight:this.wa()})}Gc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);w(this,"fullscreenerror",
{isFullscreen:e.Wa(),innerWidth:this.xa(),innerHeight:this.wa()})}Kc(f){f?this.u.xc():this.u.Mc();w(this,"visibilitychange",{hidden:f})}Kd(f,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;H(this,f,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Of(f){w(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},d)}Hc(f,h,m){a(h)||H(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Ic(f,h){if(!a(h)){var m=this.qb;"pointerdown"===f&&0!==m?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");H(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.qb=h.buttons;this.Hc(h.type,h,g)}}Za(f,h){if(this.tb&&"pointermove"!==f){var m=this.tb;m.ib||(M(m),m.Ub=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.qb);H(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===f?m="mousedown":"pointerup"===f&&(m="mouseup"),this.Hc(m,h,g),this.qb=h.buttons)}Pf(f){this.Zc=f;f=this.tb;if(-1===f.Sa){var h=Date.now(),m=h-f.Ub,c=f.Fg;m>=c&&f.Ud?(f.Ub=h,f.ib=!0,f.Qc(),f.ib=!1):f.Sa=self.setTimeout(f.me,Math.max(c-m,4))}}nf(){this.Za("pointermove",this.Zc);this.Zc=null}Ib(f,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];H(this,f,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Bc(f){window!==window.top&&window.focus();this.Hd(f.target)&&document.activeElement&&!this.Hd(document.activeElement)&&document.activeElement.blur()}Hd(f){return!f||f===document||
f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}df(){this.Rd||(this.Rd=!0,window.addEventListener("deviceorientation",f=>this.Ef(f)),window.addEventListener("deviceorientationabsolute",f=>this.Ff(f)))}cf(){this.Qd||(this.Qd=!0,window.addEventListener("devicemotion",f=>this.Df(f)))}Ef(f){w(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},
d)}Ff(f){w(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},d)}Df(f){let h=null;var m=f.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=f.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=f.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});w(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:f.interval,timeStamp:f.timeStamp},
d)}Xf(f){const h=this.u.K;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Zd&&(h.style.display="",this.Zd=!1)}Kf(f){const h=f.url;f=f.filename;const m=document.createElement("a"),c=document.body;m.textContent=f;m.href=h;m.download=f;c.appendChild(m);m.click();c.removeChild(m)}async Rf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);
h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async If(f){return await self.C3_GetSvgImageSize(f.blob)}async yf(f){await q(f.url)}Lc(){var f=[...this.Ma];this.Ma.clear();if(!this.oa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Xb.has(h)||this.Ma.add(h)})}va(f){if("function"!==typeof f.play)throw Error("missing play function");this.Xb.delete(f);let h;try{h=f.play()}catch(m){this.Ma.add(f);return}h&&h.catch(()=>{this.Xb.has(f)||this.Ma.add(f)})}Ga(f){this.Ma.delete(f);
this.Xb.add(f)}Eb(f){this.oa=!!f}Jf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Cf(f){if(f.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.za&&(this.za.style.display="none")}Sf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ld(f){window.c3_postToMessagePort&&
(f.from="runtime",window.c3_postToMessagePort(f))}wf(f,h){return this.u.vd(this.cb,"js-invoke-function",{name:f,params:h},void 0,void 0)}Ec(f){alert(f.message)}Zf(f){"entered-fullscreen"===f?(e.Lb(!0),this.Ya()):"exited-fullscreen"===f?(e.Lb(!1),this.Ya()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
async function R(e){if(e.Eg)throw Error("already initialised");e.Eg=!0;var a=e.cc.Ac("dispatchworker.js");e.Sc=await e.cc.jc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Wc=a.port1;e.Sc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.cd=await T(e)}function S(e){return[e.Wc,e.cd]}
async function T(e){const a=e.ae.length;var b=e.cc.Ac("jobworker.js");b=await e.cc.jc(b,e.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;e.Sc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);e.ae.push(b);return g.port1}
self.Oe=class{constructor(e){this.cc=e;this.F=e.F;this.F="preview"===e.s?this.F+"workers/":this.F+e.dc;this.Hg=Math.min(navigator.hardwareConcurrency||2,16);this.Sc=null;this.ae=[];this.cd=this.Wc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fa({Xg:!0,Yg:"workermain.js",Ta:["scripts/c3runtime.js"],hc:[],gd:"",Ug:"scripts/",jd:[],ne:"html5"}));"use strict";
self.fa.Da(class extends self.Ea{constructor(e){super(e,"mouse");I(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
async function U(){const e=[],a=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var b=await navigator.mediaDevices.enumerateDevices();for(const d of b){b=d.kind;const g={deviceId:d.deviceId,label:d.label,facing:d.facing||d.facingMode||""};"video"===b||"videoinput"===b?e.push(g):("audio"===b||"audioinput"===b)&&a.push(g)}}return{videoSources:e,audioSources:a}}
async function V(e,a,b){try{const d=e.u;"object"===typeof b.constraints.audio?await d.sc("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await d.sc("CAMERA");e.Aa=await navigator.mediaDevices.getUserMedia(b.constraints);a.srcObject=e.Aa;a.play();e.$d&&L(e);return{ok:!0}}catch(d){return console.warn("Error requesting camera: ",d),{ok:!1}}}
async function W(e,a){try{return await e.u.sc("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),e.Aa=await navigator.mediaDevices.getUserMedia(a.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(e.Aa,a.tag),{ok:!0}}catch(b){return console.warn("Error requesting microphone: ",b),{ok:!1}}}
async function aa(e,a){const b=document.createElement("canvas");b.width=e.videoWidth;b.height=e.videoHeight;b.getContext("2d").drawImage(e,0,0,e.videoWidth,e.videoHeight);return{snapshotUrl:await ba(b,a.format,a.quality)}}function X(e,a){e.Aa===a&&(e.Aa=null);e=a.getTracks();for(let b=0,d=e.length;b<d;++b)e[b].stop()}function ba(e,a,b){return new Promise(d=>{e.toBlob?e.toBlob(g=>d(URL.createObjectURL(g)),a,b):d(e.toDataURL(a,b))})}
self.fa.Da(class extends self.Fe{constructor(e){super(e,"user-media");this.bb=!1;this.$d=this.u.$;this.Lg=0;this.Aa=null;I(this,"get-media-sources",()=>U());Q(this,"request-camera",(a,b)=>V(this,a,b));Q(this,"request-microphone",(a,b)=>W(this,b));Q(this,"snapshot",(a,b)=>aa(a,b));Q(this,"stop",a=>this.Oc(a));self.C3UserMedia_GetVideoElement=a=>this.V.get(a);self.C3UserMedia_GetLastMediaStream=()=>this.Aa}od(e){const a=document.createElement("video");a.crossOrigin="anonymous";a.autoplay=!0;a.muted=
!0;a.playsInline=!0;a.addEventListener("canplaythrough",()=>{P(this,"video-ready",e,{width:a.videoWidth,height:a.videoHeight})});return a}Ad(){}qd(e){e.srcObject&&(X(this,e.srcObject),e.srcObject=null)}Oc(e){e.srcObject&&(X(this,e.srcObject),e.srcObject=null)}ua(){if(this.$d){var e={},a={sequenceNumber:this.Lg++,videoData:e},b=[],d=[];for(const [g,n]of this.V.entries()){if(!n.srcObject)continue;const q={};d.push(createImageBitmap(n).then(v=>{q.imageBitmap=v;b.push(v)}).catch(()=>{q.imageBitmap=null}));
e[g.toString()]=q}Promise.all(d).then(()=>w(this,"state",a,!1,b))}}});"use strict";
{const e=180/Math.PI;self.da=class extends self.Ea{constructor(a){super(a,"audio");this.Qb=this.f=null;this.Sb=this.Vc=!1;this.ra=()=>this.Ag();this.ba=[];this.D=[];this.ha=null;this.be="";this.ce=-1;this.sb=new Map;this.$c=1;this.oa=!1;this.fd=0;this.ec=1;this.Tc=0;this.ee="HRTF";this.Vd="inverse";this.fe=600;this.de=1E4;this.he=1;this.Xd=this.dd=!1;this.ke=this.u.Ne();this.ca=new Map;this.Ja=new Set;this.Xc=!1;this.ad="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Nf(b,d);this.Pb=null;
self.C3Audio_GetOutputStream=()=>this.Hf();self.C3Audio_DOMInterface=this;J(this,[["create-audio-context",b=>this.jf(b)],["play",b=>this.ag(b)],["stop",b=>this.Oc(b)],["stop-all",()=>this.yg()],["set-paused",b=>this.rg(b)],["set-volume",b=>this.wg(b)],["fade-volume",b=>this.pf(b)],["set-master-volume",b=>this.pg(b)],["set-muted",b=>this.qg(b)],["set-silent",b=>this.tg(b)],["set-looping",b=>this.og(b)],["set-playback-rate",b=>this.sg(b)],["seek",b=>this.ig(b)],["preload",b=>this.bg(b)],["unload",b=>
this.Bg(b)],["unload-all",()=>this.Cg()],["set-suspended",b=>this.ug(b)],["add-effect",b=>this.Bd(b)],["set-effect-param",b=>this.lg(b)],["remove-effects",b=>this.dg(b)],["tick",b=>this.Wf(b)],["load-state",b=>this.Lf(b)]])}async jf(a){a.isiOSCordova&&(this.dd=!0);this.fd=a.timeScaleMode;this.ee=["equalpower","HRTF","soundfield"][a.panningModel];this.Vd=["linear","inverse","exponential"][a.distanceModel];this.fe=a.refDistance;this.de=a.maxDistance;this.he=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ke||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Cd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.Cd()};this.Qb=this.f.createGain();this.Qb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.kc();try{await Promise.all(a.preloadList.map(d=>this.Gb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}Cd(){this.Sb||(this.Vc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Sb=!0)}lf(){this.Sb&&(this.Vc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Sb=!1)}Ag(){if(!this.Vc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.lf()}}X(){return this.f}kc(){return this.f.currentTime}sa(){return this.Qb}rd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.sa()}oe(a,b){a=a.toLowerCase();let d=this.ca.get(a);
d||(d=[],this.ca.set(a,d));b.ng(d.length);b.vg(a);d.push(b);this.Od(a)}Od(a){let b=this.sa();const d=this.ca.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.sa()):q.S(d[g+1].P())}}for(const g of this.ma(a))g.Te(b);this.Ba&&this.ad===a&&(this.Ba.disconnect(),this.Ba.connect(b))}Ab(){return this.$c}Bb(){return this.oa}mg(){this.Xd=!0}He(a,b){return b?this.u.Dg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}va(a){this.u.va(a)}Ga(a){this.u.Ga(a)}wd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Ue(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const g=this.ba[b];this.ba[a]=g;g.ta()?g.c():++a}this.ba.length=a}*ma(a){if(a)for(const b of this.D)self.da.Ie(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Gb(a,b,d,g,n){for(const q of this.ba)if(q.Va()===b)return await Y(q),
q;if(n)return null;g&&(this.dd||this.Xd)&&this.Ue();n="audio/webm; codecs=opus"===d&&!this.ke;g&&n&&this.mg();a=!g||this.dd||n?new self.Ce(this,a,b,d,g,n):new self.Ae(this,a,b,d,g);this.ba.push(a);await Y(a);return a}async zc(a,b,d,g,n){for(const q of this.D)if(q.Va()===b&&(q.ic()||n))return q.Xe(g),q;a=await this.Gb(a,b,d,n);g="html5"===a.Pc?new self.Be(a.i,a,g):new self.De(a.i,a,g);this.D.push(g);return g}af(a){let b=this.sb.get(a);if(!b){let d=null;b={hd:0,Tg:new Promise(g=>d=g),resolve:d};this.sb.set(a,
b)}b.hd++}eg(a){const b=this.sb.get(a);if(!b)throw Error("expected pending tag");b.hd--;0===b.hd&&(b.resolve(),this.sb.delete(a))}wc(a){a||(a=this.be);return(a=this.sb.get(a))?a.Tg:Promise.resolve()}Hb(){if(0<this.Ja.size)L(this);else for(const a of this.D)if(a.sd()){L(this);break}}ua(){for(var a of this.Ja)a.ua();a=this.kc();for(var b of this.D)b.ua(a);b=this.D.filter(d=>d.sd()).map(d=>d.Ua());w(this,"state",{tickCount:this.ce,audioInstances:b,analysers:[...this.Ja].map(d=>d.Ke())});0===b.length&&
0===this.Ja.size&&this.Tb&&(this.u.fg(this.le),this.Tb=!1)}rc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async ag(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.be=q;this.af(q);try{this.ha=await this.zc(b,d,g,q,n),x?(this.ha.Db(!0),this.ha.We(x.x,x.y,x.angle,
x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.Ye(x.uid)):this.ha.Db(!1),this.ha.Play(v,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.eg(q)}L(this)}Oc(a){a=a.tag;for(const b of this.ma(a))b.na()}yg(){for(const a of this.D)a.na()}rg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Cb();this.Hb()}wg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Fb(a)}async pf(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.wc(b);for(const n of this.ma(b))n.Je(d,g,a);this.Hb()}pg(a){this.$c=a.vol;for(const b of this.D)b.Nb()}qg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.xd(a)}tg(a){this.oa=a.isSilent;this.u.Eb(this.oa);for(const b of this.D)b.Mb()}og(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.uc(a)}async sg(a){const b=a.tag;a=a.rate;await this.wc(b);for(const d of this.ma(b))d.zd(a)}async ig(a){const b=a.tag;a=a.pos;await this.wc(b);for(const d of this.ma(b))d.tc(a)}async bg(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.zc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Bg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}Cg(){for(const a of this.ba)a.c();this.ba.length=0}ug(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.vc(a);a&&this.f.suspend&&this.f.suspend()}Wf(a){this.ec=a.timeScale;this.Tc=a.gameTime;this.ce=a.tickCount;if(0!==
this.fd)for(var b of this.D)b.Ia();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.yd(d.x,d.y,d.angle)}}async Bd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.ue(this,...g);else if("delay"===b)g=new self.se(this,...g);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.re(this,b.aa,...g);g.jg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ve(this,...g);else if("phaser"===b)g=new self.xe(this,...g);else if("gain"===b)g=new self.we(this,...g);else if("tremolo"===b)g=new self.ze(this,...g);else if("ringmod"===b)g=new self.ye(this,...g);else if("distortion"===b)g=new self.te(this,...g);else if("compressor"===b)g=new self.qe(this,...g);else if("analyser"===b)g=new self.pe(this,...g);else throw Error("invalid effect type");this.oe(d,
g);this.Nd()}lg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(d,g,n,q),this.Nd())}dg(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.c();this.ca.delete(a);this.Od(a)}}$e(a){this.Ja.add(a);this.Hb()}cg(a){this.Ja.delete(a)}Nd(){this.Xc||(this.Xc=!0,Promise.resolve().then(()=>this.mf()))}mf(){const a={};for(const [b,d]of this.ca)a[b]=d.map(g=>g.Ua());w(this,"fxstate",{fxstate:a});this.Xc=!1}async Lf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ta()&&1===b||(d.ta()||2!==b)&&d.na();for(const g of this.ca.values())for(const n of g)n.c();this.ca.clear();this.ec=a.timeScale;this.Tc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.u.Eb(this.oa);this.$c=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.Bd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.xf(g,b)));this.Hb()}async xf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.zc(d,g,n,v,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Re(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Xa();b.Dc(a)}}}Nf(a,b){this.Ba&&this.Ba.disconnect();this.ad=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.rd(this.ad))}Hf(){this.Pb||(this.Pb=this.f.createMediaStreamDestination(),
this.Qb.connect(this.Pb));return this.Pb.stream}static Ie(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ze(a){return a*e}static Ge(a){return Math.pow(10,a/20)}static pd(a){return Math.max(Math.min(self.da.Ge(a),1),0)}static Qe(a){return Math.log(a)/Math.log(10)*20}static Pe(a){return self.da.Qe(Math.max(Math.min(a,1),0))}static Og(a,b){return 1-Math.exp(-b*a)}};self.fa.Da(self.da)}"use strict";function Y(e){e.Vb||(e.Vb=e.Cc());return e.Vb}
self.ld=class{constructor(e,a,b,d,g){this.i=e;this.Jg=a;this.Ca=b;this.R=d;this.Gg=g;this.Pc="";this.Vb=null}c(){this.Vb=this.i=null}Cc(){}X(){return this.i.X()}mc(){return this.Jg}Va(){return this.Ca}lc(){return this.R}ta(){return this.Gg}ea(){}};"use strict";
self.Ae=class extends self.ld{constructor(e,a,b,d,g){super(e,a,b,d,g);this.Pc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.mb=this.nb=null;this.J.addEventListener("canplaythrough",()=>!0);this.rb=this.X().createGain();this.pb=null;this.J.addEventListener("canplay",()=>{this.nb&&(this.nb(),this.mb=this.nb=null);!this.pb&&this.J&&(this.pb=this.X().createMediaElementSource(this.J),this.pb.connect(this.rb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,n);this.mb&&(this.mb(n),this.mb=this.nb=null)})}c(){this.i.wd(this);this.rb.disconnect();this.rb=null;this.pb.disconnect();this.pb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Cc(){return new Promise((e,a)=>{this.nb=e;this.mb=a;this.J.src=this.Ca})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function ca(e){if(e.ya)return e.ya;var a=e.i.u;if("cordova"===a.s&&a.td(e.Ca)&&a.jb)e.ya=await a.yb(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.ya=await a.arrayBuffer()}}async function ea(e){if(e.aa)return e.aa;e.aa=await e.i.He(e.ya,e.Ig);e.ya=null}
self.Ce=class extends self.ld{constructor(e,a,b,d,g,n){super(e,a,b,d,g);this.Pc="webaudio";this.aa=this.ya=null;this.Ig=!!n}c(){this.i.wd(this);this.aa=this.ya=null;super.c()}async Cc(){try{await ca(this),await ea(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.md=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Ob=e++;this.M=this.X().createGain();this.M.connect(this.sa());this.B=null;this.kb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.W=this.la=this.G=!1;this.vb=1;this.Ka=!1;this.qa=1;a=this.i.fd;this.Yc=1===a&&!this.ta()||2===a;this.gb=this.ga=-1;this.je=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}X(){return this.i.X()}sa(){return this.i.rd(this.Z)}Ab(){return this.i.Ab()}zb(){return this.Yc?
this.i.Tc:performance.now()/1E3}mc(){return this.L.mc()}Va(){return this.L.Va()}lc(){return this.L.lc()}ta(){return this.L.ta()}Xe(a){this.Z=a}T(){}ic(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}sd(){return!this.H&&!this.T()}Fa(){}ea(){return this.L.ea()}Play(){}na(){}Xa(){}Cb(){}Fb(a){this.vb=a;this.M.gain.cancelScheduledValues(0);this.gb=-1;this.M.gain.value=this.nc()}Je(a,b,d){if(!this.Ka){a*=this.Ab();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.kc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.vb=a;this.gb=b;this.je=d}}Nb(){this.Fb(this.vb)}ua(a){-1!==this.gb&&a>=this.gb&&(this.gb=-1,this.je&&this.na(),this.i.rc("fade-ended",this.Z,this.Ob))}nc(){const a=this.vb*this.Ab();return isFinite(a)?a:0}xd(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Mb())}Bb(){return this.i.Bb()}Mb(){}uc(){}zd(a){this.qa!==a&&(this.qa=a,this.Ia())}Ia(){}tc(){}vc(){}Db(a){a=!!a;this.kb!==a&&((this.kb=a)?(this.B||(this.B=this.X().createPanner(),this.B.panningModel=this.i.ee,this.B.distanceModel=
this.i.Vd,this.B.refDistance=this.i.fe,this.B.maxDistance=this.i.de,this.B.rolloffFactor=this.i.he),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.sa())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}We(a,b,d,g,n,q){this.kb&&(this.yd(a,b,d),a=self.da.Ze,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}yd(a,b,d){this.kb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Ye(a){this.ga=a}oc(){}Te(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Ob,tag:this.Z,duration:this.ea(),volume:this.vb,isPlaying:this.IsPlaying(),playbackTime:this.Fa(),playbackRate:this.qa,uid:this.ga,bufferOriginalUrl:this.mc(),bufferUrl:"",bufferType:this.lc(),isMusic:this.ta(),isLooping:this.W,isMuted:this.Ka,resumePosition:this.oc(),pan:this.Le()}}Dc(a){this.zd(a.playbackRate);this.xd(a.isMuted)}Le(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Re(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Db(!1)}}}"use strict";
self.Be=class extends self.md{constructor(e,a,b){super(e,a,b);this.L.rb.connect(this.M);this.L.onended=()=>this.Fc()}c(){this.na();this.L.rb.disconnect();super.c()}O(){return this.L.O()}Fc(){this.H=!0;this.ga=-1;this.i.rc("ended",this.Z,this.Ob)}T(){return this.O().ended}ic(){return this.H?!0:this.T()}Fa(){let e=this.O().currentTime;this.W||(e=Math.min(e,this.ea()));return e}Play(e,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==e&&(d.loop=e);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.va(d);this.G=this.H=!1;this.W=e;this.qa=1}na(){const e=this.O();e.paused||e.pause();this.i.Ga(e);this.H=!0;this.G=!1;this.ga=-1}Xa(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.Ga(e);this.G=!0}}Cb(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Mb(){this.O().muted=this.Ka||this.Bb()}uc(e){e=!!e;this.W!==e&&
(this.W=e,this.O().loop=e)}Ia(){let e=this.qa;this.Yc&&(e*=this.i.ec);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}tc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}oc(){return this.Fa()}vc(e){e?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Z(e){e.j&&e.j.disconnect();e.j=null;e.ab=null}
self.De=class extends self.md{constructor(e,a,b){super(e,a,b);this.j=null;this.Yb=d=>this.Fc(d);this.Uc=!0;this.ab=null;this.N=this.Zb=this.$b=0;this.bd=1}c(){this.na();Z(this);this.Yb=null;super.c()}Fc(e){this.G||this.la||e.target!==this.ab||(this.H=this.Uc=!0,this.ga=-1,Z(this),this.i.rc("ended",this.Z,this.Ob))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Uc}ic(){return!this.j||this.H?!0:this.T()}Fa(){let e;e=this.G?this.N:this.Zb+(this.zb()-this.$b)*this.qa;this.W||(e=Math.min(e,this.ea()));
return e}Play(e,a,b,d){this.bd=1;this.Fb(a);Z(this);this.j=this.X().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Yb;this.j.loop=e;this.j.start(d,b);this.G=this.H=this.Uc=!1;this.W=e;this.qa=1;this.$b=this.zb();this.Zb=b}na(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ga=-1}Xa(){this.G||this.H||this.T()||(this.N=this.Fa(),this.W&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Cb(){!this.G||this.H||this.T()||(Z(this),this.j=
this.X().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.W,this.Nb(),this.Ia(),this.j.start(0,this.N),this.$b=this.zb(),this.Zb=this.N,this.G=!1)}nc(){return super.nc()*this.bd}Mb(){this.bd=this.Ka||this.Bb()?0:1;this.Nb()}uc(e){e=!!e;this.W!==e&&(this.W=e,this.j&&(this.j.loop=e))}Ia(){let e=this.qa;this.Yc&&(e*=this.i.ec);this.j&&(this.j.playbackRate.value=e)}tc(e){this.H||this.T()||(this.G?this.N=e:(this.Xa(),this.N=e,this.Cb()))}oc(){return this.N}vc(e){e?
this.IsPlaying()?(this.la=!0,this.N=this.Fa(),this.W&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Z(this),this.j=this.X().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.W,this.Nb(),this.Ia(),this.j.start(0,this.N),this.$b=this.zb(),this.Zb=this.N,this.la=!1)}Dc(e){super.Dc(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.X();this.Yd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}ng(a){this.Yd=a}vg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Z,params:this.g}}}
self.ue=class extends e{constructor(a,b,d,g,n,q,v){super(a);this.R="filter";this.g=[b,d,g,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.A=this.f.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=g;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}c(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,g)}}};self.se=class extends e{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.ob=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.fb=this.o();this.fb.gain.value=d;this.l.connect(this.ob);this.l.connect(this.a);this.ob.connect(this.b);this.ob.connect(this.U);this.U.connect(this.fb);this.fb.connect(this.ob)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.ob.disconnect();this.U.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){const n=self.da.pd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.fb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.re=class extends e{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Td=this.Sd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.eb=this.f.createConvolver();this.eb.normalize=d;this.eb.buffer=b;this.l.connect(this.eb);this.l.connect(this.a);this.eb.connect(this.b)}c(){this.l.disconnect();this.eb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}jg(a,b){this.Sd=a;this.Td=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Sd;a.bufferUrl="";a.bufferType=this.Td;return a}};self.ve=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.hb=this.o();this.hb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.v=this.f.createOscillator();this.v.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.hb);this.hb.connect(this.U);this.v.connect(this.I);this.I.connect(this.U.delayTime);this.v.start(0)}c(){this.v.stop(0);this.l.disconnect();this.U.disconnect();this.v.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.hb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.hb.gain,b/100,d,g)}}};self.xe=class extends e{constructor(a,b,d,g,n,q,v){super(a);this.R="phaser";this.g=[b,d,g,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.A=this.f.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=g;this.v=this.f.createOscillator();this.v.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.v.connect(this.I);this.I.connect(this.A.frequency);this.v.start(0)}c(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,g)}}};self.we=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,d,g){const n=self.da.pd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.ze=class extends e{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.f.createOscillator();this.v.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.v.connect(this.I);this.I.connect(this.h.gain);this.v.start(0)}c(){this.v.stop(0);this.v.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.ye=class extends e{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.ub=this.o();this.ub.gain.value=
0;this.v=this.f.createOscillator();this.v.frequency.value=b;this.v.connect(this.ub.gain);this.v.start(0);this.l.connect(this.ub);this.l.connect(this.a);this.ub.connect(this.b)}c(){this.v.stop(0);this.v.disconnect();this.ub.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.te=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.bc=this.o();this.ac=this.o();this.kg(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.fc=this.f.createWaveShaper();this.Rc=new Float32Array(65536);this.rf(b,d);this.fc.curve=this.Rc;this.l.connect(this.bc);this.l.connect(this.a);this.bc.connect(this.fc);this.fc.connect(this.ac);
this.ac.connect(this.b)}c(){this.l.disconnect();this.bc.disconnect();this.fc.disconnect();this.ac.disconnect();this.b.disconnect();this.a.disconnect();super.c()}kg(a,b){.01>a&&(a=.01);this.bc.gain.value=a;this.ac.gain.value=Math.pow(1/a,.6)*b}rf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.xg(g,a,b);this.Rc[32768+d]=g;this.Rc[32768-d-1]=-g}}xg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Og(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.qe=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}};
self.pe=class extends e{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Wd=new Float32Array(this.h.frequencyBinCount);this.ie=new Uint8Array(b);this.ge=this.Na=0;this.i.$e(this)}c(){this.i.cg(this);this.h.disconnect();super.c()}ua(){this.h.getFloatFrequencyData(this.Wd);this.h.getByteTimeDomainData(this.ie);const a=this.h.fftSize;let b=this.Na=0;for(var d=0;d<a;++d){let g=(this.ie[d]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}d=self.da.Pe;this.Na=d(this.Na);this.ge=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}Ke(){return{tag:this.Z,index:this.Yd,peak:this.Na,rms:this.ge,binCount:this.h.frequencyBinCount,freqBins:this.Wd}}}}"use strict";function ha(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>w(e,"sw-message",a.data))}
function ia(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.fa.Da(class extends self.Ea{constructor(e){super(e,"browser");this.s="";J(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ha(this)],
["alert",a=>this.Ec(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Jc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ia(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.bh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.fa.Lb(!0),this.u.Nc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.fa.Lb(!1),this.u.Nc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{w(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{w(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{w(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{w(this,"backbutton")})}Ec(e){alert(e.message)}Jc(e){e=e.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";async function ja(e,a){a=a.type;let b=!0;0===a?b=await ka():1===a&&(b=await la());w(e,"permission-result",{type:a,result:b})}
async function ka(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function la(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.fa.Da(class extends self.Ea{constructor(e){super(e,"touch");I(this,"request-permission",a=>ja(this,a))}});
